#!/bin/sh
# Copied from the Arch Linux wiki:
# https://wiki.archlinux.org/index.php?title=Pacman_tips&oldid=380070#Identify_files_not_owned_by_any_package
# As such, it is distributed under the GNU Free Documentation License
# https://www.gnu.org/copyleft/fdl.html
# regardless of the license applied to the repository as a whole.

tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
db=$tmp/db
fs=$tmp/fs

mkdir "$tmp"
trap 'rm -rf "$tmp"' EXIT

pacman -Qlq | sort -u > "$db"

find /etc /opt /usr ! -name lost+found \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"

comm -23 "$fs" "$db"
